---
- name: Installation du Master K3s
  hosts: k3s_master
  become: true
  tasks:
    - name: Installation de K3s (Master)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s  # Ne lance pas si déjà installé

    - name: Attendre que le Master soit prêt
      wait_for:
        port: 6443
        delay: 5

    - name: Récupération du Token du Node
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token_base64

    - name: Décodage du Token
      set_fact:
        k3s_token: "{{ node_token_base64['content'] | b64decode | trim }}"

    # On partage cette variable avec les autres machines du playbook
    - name: Enregistrement du Token et IP pour les workers
      add_host:
        name: "K3S_TOKEN_HOLDER"
        token: "{{ k3s_token }}"
        master_ip: "{{ ansible_host }}"

- name: Installation des Workers K3s
  hosts: k3s_workers
  become: true
  tasks:
    - name: Installation de K3s (Agent/Worker)
      shell: >
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['K3S_TOKEN_HOLDER']['master_ip'] }}:6443 K3S_TOKEN={{ hostvars['K3S_TOKEN_HOLDER']['token'] }} sh -
      args:
        creates: /usr/local/bin/k3s-agent

- name: Configuration de l'accès Admin (Sur ta machine locale)
  hosts: k3s_master
  become: true
  tasks:
    - name: Récupération du fichier kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: yes

- name: Finalisation sur l'Admin Box
  hosts: localhost
  connection: local
  tasks:
    - name: Correction de l'IP dans le fichier de config
      replace:
        path: ~/.kube/config
        regexp: '127.0.0.1'
        replace: '10.10.10.20' # IP de ton Master
        
    - name: Installation de kubectl (Si pas déjà là)
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
      args:
        creates: /usr/local/bin/kubectl
      become: true